abinco/abinco/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("inventario/", include('inventario.urls'), name='inventario'),
    path("pedidos/", include('pedidos.urls'), name='pedidos'),
    path('', include('cuentas.urls'), name='cuentas'),
]

abinco/abinco_app/urls.py
from django.urls import path
from . import views

app_name = 'abinco_app'
urlpatterns = [
    path('', views.index, name='index'),
]

abinco/cuentas/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cuentas, name='cuentas'),
    path('registrarse/', views.registrarse, name='registrarse'),
    path('iniciarsesion/', views.iniciarsesion, name='iniciarsesion'),
    path('cerrarsesion/', views.cerrarsesion, name='cerrarsesion'),
]

abinco/inventario/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.productos, name='productos'),
    path('productos/<int:id>/', views.detalle, name='detalle'),
    path('productos/<int:id>/actualizar/', views.actualizar, name='actualizar'),
]

abinco/pedidos/urls.py
from django.urls import path
from . import views

app_name = 'inventario'
urlpatterns = [
    path('', views.pedidos, name='pedidos'),
]

abinco/abinco_app/models.py
from django.db import models

class ClaseBase(models.Model):
    creado_el = models.DateField(auto_now_add=True)
    actualizado_el = models.DateField(auto_now=True)
    
    class Meta:
        abstract = True

class Categoria(ClaseBase):
    nombre = models.CharField(max_length=100)
    
    def __str__(self):
        return self.nombre

class Marca(ClaseBase):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

class Ubicacion(ClaseBase):
    zona = models.CharField(max_length=100)

    def __str__(self):
        return self.zona


class Producto(ClaseBase):
    codigo = models.CharField(max_length=30)
    nombre = models.CharField(max_length=200)
    descripcion = models.TextField()
    stock = models.IntegerField()
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    marca = models.ForeignKey(Marca, on_delete=models.CASCADE)
    ubicacion = models.ForeignKey(Ubicacion, on_delete=models.CASCADE)

    def __str__(self):
        return self.codigo

abinco/cuentas/models.py
from django.db import models

# Create your models here.

abinco/pedidos/models.py
from django.db import models
from inventario.models import Producto, ClaseBase

class Pedido(ClaseBase):
    pass

abinco/cuentas/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

class FormularioCreacionUsuario(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(FormularioCreacionUsuario, self).__init__(*args, **kwargs)

        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None
            self.fields[fieldname].widget.attrs.update({'class': 'form-control'})


class FormularioInicioSesion(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(FormularioInicioSesion, self).__init__(*args, **kwargs)

        for fieldname in ['username', 'password']:
            self.fields[fieldname].widget.attrs.update({'class': 'form-control'})

abinco/inventario/forms.py
from django.forms import ModelForm, HiddenInput
from .models import Producto

class FormularioProducto(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs) 
        self.fields['nombre'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Ej. Caño PVC'})
        self.fields['codigo'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Ej. EAN765765765'})
        self.fields['marca'].widget.attrs.update({'class': 'form-select', 'placeholder': 'Ej. Tigre'})
        self.fields['categoria'].widget.attrs.update({'class': 'form-select', 'placeholder': 'Ej. Caño'})
        self.fields['stock'].widget.attrs.update({'class': 'form-control'})
        self.fields['ubicacion'].widget.attrs.update({'class': 'form-select', 'placeholder': 'Ej. A1'})
        self.fields['descripcion'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Escribir una descripción...'})

    class Meta:
        model = Producto
        fields = ['nombre', 'codigo', 'marca', 'categoria', 'stock', 'ubicacion', 'descripcion']

abinco/abinco_app/views.py
from django.http import HttpResponse
from django.shortcuts import render

def index(request):
    return HttpResponse("Hola Mundo")

abinco/cuentas/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .forms import FormularioCreacionUsuario, FormularioInicioSesion
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.shortcuts import redirect
from django.db import IntegrityError

def cuentas(request):
    if request.user.is_authenticated:
        return redirect('/inventario')
    else:
        return redirect('iniciarsesion')

def registrarse(request):
    if request.method == 'GET':
        return render(request, 'registrarse.html', {'form':FormularioCreacionUsuario})
    else:
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.create_user(request.POST['username'], password = request.POST['password1'])
                user.save()
                login(request, user)
                return redirect('inventario')
            except IntegrityError:
                return render(request, 'registrarse.html', {'form': FormularioCreacionUsuario, 'error':'El nombre de usuario ya existe'})    
        else:
            return render(request, 'registrarse.html', {'form': FormularioCreacionUsuario, 'error':'Las contraseñas no coinciden'})

def iniciarsesion(request):
    if request.method == 'GET':
        return render(request, 'iniciarsesion.html', {'form': FormularioInicioSesion})
    else:
        user = authenticate(request, username=request.POST['username'], password= request.POST['password'])
        if user is None:
            return render(request, 'iniciarsesion.html', {'form': FormularioInicioSesion(), 'error': 'El usuario o la contraseña son incorrectos'})
        else:
            login(request, user)
            return redirect('/inventario')

def cerrarsesion(request):
    logout(request)
    return redirect('iniciarsesion')

abinco/inventario/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from .models import Producto, Marca, Categoria, Ubicacion
from django.contrib.auth.decorators import login_required
from .forms import FormularioProducto
import logging

@login_required
def productos(request):
    busqueda = request.GET.get('buscarProducto')
    if busqueda:
        productos = Producto.objects.filter(codigo__icontains=busqueda)
    else:
        productos = Producto.objects.all()
    return render(request, 'inventario.html', {'busqueda':busqueda, 'productos':productos})

@login_required
def detalle(request, id):
    if request.method == 'GET':
        producto = get_object_or_404(Producto, id=id)
        form = FormularioProducto(instance=producto)
        pk = id
        return render(request, 'detalle.html', {'form':form, 'pk':pk})


@login_required
def actualizar(request, id):
    producto = Producto.objects.get(id=id)
    producto.codigo = request.POST.get('codigo')
    producto.marca = Marca.objects.get(pk=request.POST.get('marca'))
    producto.categoria = Categoria.objects.get(pk=request.POST.get('categoria'))
    producto.stock = request.POST.get('stock')
    producto.ubicacion = Ubicacion.objects.get(pk=request.POST.get('ubicacion'))
    producto.descripcion = request.POST.get('descripcion')
    producto.save()
    mensaje = "Se actualizó el registro"
    return redirect('detalle', id=id)

abinco/pedidos/views.py
from django.shortcuts import render

def pedidos(request):
    return render(request, 'hola')

abinco/abinco/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Abinco Intranet</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" href="#">Abinco</a>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Inicio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Pedidos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'productos' %}">Inventario</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        {{ user.username }}
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'cerrarsesion' %}">Cerrar Sesion</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="#">Perfil</a></li>
                    </ul>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'registrarse' %}">Registrarse</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'iniciarsesion' %}">Iniciar Sesion</a>
                </li>
                {% endif %}
            </ul>
            </div>
        </div>
    </nav>
    <div class="container mt-5">
        {% block content %}
        
        {% endblock content %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
</body>
</html>

abinco/abinco_app/templates/home.html
{% extends 'base.html' %}
{% block content %}
    <form action="">
        <div class="mb-3">
            <label class="form-label">Buscar Producto por código</label>
            <input type="text" name="buscarProducto" class="form-control" />
        </div>
        <button class="btn btn-primary">
            Buscar Producto
        </button>
    </form>
    <p>Producto buscado: {{ busqueda }}</p>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Código</th>
                <th scope="col">Nombre</th>
                <th scope="col">Stock</th>
                <th scope="col">Categoria</th>
                <th scope="col">Marca</th>
                <th scope="col">Ubicación</th>
            </tr>
        </thead>
        <tbody>
            {% for producto in productos %}
                <tr>
                    <td><a href="{% url 'abinco_app:detalle' producto.codigo %}">{{ producto.codigo }}</a></td>
                    <td>{{ producto.nombre }}</td>
                    <td>{{ producto.stock }}</td>
                    <td>{{ producto.categoria }}</td>
                    <td>{{ producto.marca }}</td>
                    <td>{{ producto.ubicacion }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

abinco/cuentas/templates/iniciarsesion.html
{% extends 'base.html' %}
{% block content %}
<div class="card mb-3">
    <div class="row g-0">
        <div>
            <div class="card-body">
                <h5 class="card-title">Iniciar Sesión</h5>
                {% if error %}
                <div class="alert alert-danger mt-3" role="alert">
                    {{ error }}
                </div>
                {% endif %}
                <p class="card-text">
                    <form method="POST">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Ingresar</button>
                    </form>
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

abinco/cuentas/templates/registrarse.html
{% extends 'base.html' %}
{% block content %}
<div class="card mb-3">
    <div class="row g-0">
        <div>
            <div class="card-body">
                <h5 class="card-title">Registrarse</h5>
                {% if error %}
                <div class="alert alert-danger mt-3">
                    {{ error }}
                </div>
                {% endif %}
                <p class="card-text">
                    <form method="POST">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Registrarse</button>
                    </form>
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

abinco/inventario/templates/detalle.html
{% extends 'base.html' %}
{% block content %}
    <div class="container-md position-absolute top-50 start-50 translate-middle">
        <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'productos' %}">Inventario</a></li>
                <li class="breadcrumb-item active" aria-current="page">{{ form.codigo.value }}</li>
            </ol>
        </nav>
        {% if mensaje %}
        <p class="alert">{{ mensaje }}</p>
        {% endif %}
        <form action="{% url 'actualizar' pk %}" method="POST">
            {% csrf_token %}
            <ul class="list-group">
                <li class="list-group-item">
                    <div class="input-group mb-3">
                        <span class="input-group-text" id="basic-addon1">Nombre</span>
                        {{ form.nombre }}
                    </div>
                </li>
                <li class="list-group-item">
                    <div class="input-group mb-3">
                        <span class="input-group-text" id="basic-addon1">Código</span>
                        {{ form.codigo }}
                    </div>
                </li>
                <li class="list-group-item">
                    <div class="input-group mb-3">
                        <span class="input-group-text" id="basic-addon1">Stock</span>
                        {{ form.stock }}
                    </div>
                </li>
                <li class="list-group-item">
                    <div class="input-group mb-3">
                        <span class="input-group-text" id="basic-addon1">Categoria</span>
                        {{ form.categoria }}
                    </div>
                </li>
                <li class="list-group-item">
                    <div class="input-group mb-3">
                        <span class="input-group-text" id="basic-addon1">Marca</span>
                        {{ form.marca }}
                    </div>
                </li>
                <li class="list-group-item">
                    <div class="input-group mb-3">
                        <span class="input-group-text" id="basic-addon1">Ubicación</span>
                        {{ form.ubicacion }}
                    </div>
                </li>
                <li class="list-group-item">
                    <div class="input-group mb-3">
                        <span class="input-group-text" id="basic-addon1">Descripción</span>
                        {{ form.descripcion }}
                    </div>
                </li>
            </ul>
            <button type="submit" class="btn btn-primary">Guardar</button>
        </form>
    </div>
{% endblock content %}

abinco/inventario/templates/inventario.html
{% extends 'base.html' %}
{% block content %}
    <form action="">
        <div class="mb-3">
            <label class="form-label">Buscar Producto por código</label>
            <input type="text" name="buscarProducto" class="form-control" />
        </div>
        <button class="btn btn-primary">
            Buscar Producto
        </button>
        <a href="{% url 'productos' %}" class="btn btn-primary">
                Limpiar Busqueda
        </a>
    </form>
    <p class="text-muted fst-italic">Producto buscado: 
        {% if busqueda %}
            {{ busqueda }}
        {% else %}
            Todos
        {% endif %}
    </p>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Código</th>
                <th scope="col">Nombre</th>
                <th scope="col">Stock</th>
                <th scope="col">Categoria</th>
                <th scope="col">Marca</th>
                <th scope="col">Ubicación</th>
            </tr>
        </thead>
        <tbody>
            {% for producto in productos %}
                <tr>
                    <td><a href="{% url 'detalle' producto.id %}">{{ producto.codigo }}</a></td>
                    <td>{{ producto.nombre }}</td>
                    <td>{{ producto.stock }}</td>
                    <td>{{ producto.categoria }}</td>
                    <td>{{ producto.marca }}</td>
                    <td>{{ producto.ubicacion }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}